import type { Project } from "./types"

export const projectsData: Project[] = [
  {
    id: "messit",
    slug: "messit-dining-platform",
    title: "MessIT – Digital Dining Platform",
    image: "/projects/messit.jpg",
    imageAlt: "MessIT – Digital Dining Platform for University Students",
    briefDescription:
      "Led product development of MessIT, a digital dining platform adopted by 10,000+ students at VIT University, replacing manual mess-menu processes with a seamless digital experience.",
    problem:
      "University dining was entirely manual — students had no visibility into daily menus, couldn't provide structured feedback, and administrators had no data to improve operations. The process was slow, inefficient, and frustrating for 10,000+ students.",
    detailedDescription:
      "MessIT is a digital dining platform built to replace the outdated manual mess-menu processes at VIT University, one of India's largest residential campuses with 30,000+ on-campus students. As the product lead, I drove the end-to-end development — from user discovery and requirements gathering to launch and adoption.\n\nThe platform gave students real-time access to daily menus, enabled structured feedback collection, and provided administrators with actionable data to improve dining operations at scale.",
    outcomeBullets: [
      "Adopted by 10,000+ of VIT University's on-campus students",
      "Replaced 100% of manual mess-menu processes",
      "Enabled structured feedback collection for dining administrators",
      "Improved operational visibility and menu planning efficiency",
    ],
    technologies: [
      "Product Strategy",
      "User Research",
      "Agile",
      "PRD",
      "Roadmapping",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "10,000+",
    kpiLabel: "Students Adopted",
    kpiValue: "Full Campus Rollout",
    demoUrl: "https://play.google.com/store/apps/details?id=com.vinnovateit.messit&pcampaignid=web_share",
    youtubeUrl: "",
  },
  {
    id: "bunkbuddies",
    slug: "bunkbuddies-roommate-matching",
    title: "BunkBuddies – Roommate Matching Platform",
    image: "/projects/bunkbuddies.png",
    imageAlt: "BunkBuddies – University Roommate Matching Platform",
    briefDescription:
      "Drove end-to-end launch as Project Lead of the university's first roommate matching platform, gaining 1,250+ users on launch day.",
    problem:
      "Finding a compatible roommate at university was entirely word-of-mouth — no structured platform existed. Students relied on social media groups and random assignments, leading to poor roommate compatibility and avoidable conflicts.",
    detailedDescription:
      "BunkBuddies was the university's first dedicated roommate matching platform. As Project Lead, I owned the full product lifecycle — from identifying the problem through user interviews to defining matching criteria, coordinating the engineering team, and executing the launch strategy.\n\nThe platform matched students based on lifestyle preferences, study habits, and personal preferences, significantly improving roommate compatibility.",
    outcomeBullets: [
      "1,250+ users acquired on launch day",
      "First-ever roommate matching platform at the university",
      "Drove full end-to-end product launch as Project Lead",
      "Replaced unstructured social media roommate search process",
    ],
    technologies: [
      "Product Management",
      "User Discovery",
      "MVP Development",
      "Launch Strategy",
      "A/B Testing",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "1,250+",
    kpiLabel: "Users on Launch Day",
    kpiValue: "University's First Platform",
    demoUrl: "https://bunkbuddies.vinnovateit.com",
    youtubeUrl: "",
  },
  {
    id: "ai-whatsapp-navigator",
    slug: "ai-whatsapp-patient-navigator",
    title: "AI-Powered WhatsApp Patient Navigator",
    image: "/projects/jc-foundation.png",
    imageAlt: "AI WhatsApp Navigator – Automated Patient Guidance System",
    briefDescription:
      "Deployed an AI-powered WhatsApp navigator using NLP models to automate end-to-end patient guidance for a secondary consultation platform serving 500+ patients/month, reducing wait times by 15%.",
    problem:
      "JC Foundation's secondary consultation platform serves 500+ cancer patients per month but struggled with high manual overhead in patient guidance. Long wait times and inconsistent communication created friction in an already stressful patient journey.",
    detailedDescription:
      "At JC Foundation, I defined the product roadmap and feature requirements for an AI-enabled secondary consultation platform. The flagship feature was an AI-powered WhatsApp navigator that used NLP models to automate the end-to-end patient guidance journey.\n\nI also conducted 30+ user discovery interviews with our partnered oncologists to map workflows, identify bottlenecks, and validate pricing models — ensuring the product was grounded in real clinical needs.",
    outcomeBullets: [
      "15% reduction in patient wait times",
      "500+ patients served per month on the platform",
      "Automated end-to-end patient guidance via WhatsApp",
      "30+ oncologist/patient interviews conducted for user discovery",
      "Defined full product roadmap and feature requirements",
    ],
    technologies: [
      "NLP",
      "WhatsApp Business API",
      "Product Roadmapping",
      "User Research",
      "PRD",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "15%",
    kpiLabel: "Wait Time Reduction",
    kpiValue: "500+ Patients/Month",
    demoUrl: "https://www.jarurat.care",
    youtubeUrl: "",
  },
  {
    id: "agentic-ai-platform",
    slug: "agentic-ai-cybersecurity-platform",
    title: "Agentic AI Platform – Cybersecurity SMB Navigator",
    image: "/projects/agentic-ai.png",
    imageAlt: "Agentic AI Platform for SMB Cybersecurity Navigation",
    briefDescription:
      "Shipped 4 production AI products in 6 months and led GenAI product analysis and feature discovery for Value Aligners — an Agentic AI platform helping SMBs without a CISO navigate 9,000+ cybersecurity solutions and select the right tools based on their profile, needs, and budget.",
    problem:
      "Most SMBs operate without a CISO and face an overwhelming cybersecurity market of 9,000+ solutions with no clear way to evaluate what they actually need. The cost of wrong decisions is high — both financially and in terms of security risk. Value Aligners needed to define the right AI-powered features to cut through this complexity and deliver precise, budget-aware recommendations.",
    detailedDescription:
      "Value Aligners is an Agentic AI platform serving SMBs across four core products: Agentic GRC & Compliance (SOC 2, ISO 27001 workflows), Virtual CISO Advisory (AI-powered security strategy), Pre-Vetted Marketplace (curated, matched security providers), and Cybersecurity Analytics (real-time risk dashboards).\n\nAs PM Intern, I Shipped 4 production AI products in 6 months, identifying which AI capabilities would deliver the most value for SMBs without dedicated security teams. I identified and resolved release bottlenecks across engineering teams, redesigned coordination processes to improve development throughput, and managed JIRA and Confluence workflows, sprint planning, and release tracking to ensure milestone completion.\n\nThe platform's recommendation engine matches SMBs to vetted cybersecurity solutions based on their specific risk profile, compliance requirements, and budget — acting as an always-on Virtual CISO for companies that can't afford one.",
    outcomeBullets: [
      "Led GenAI feature discovery across 4 product lines serving budget-constrained SMBs",
      "Identified and resolved release bottlenecks improving engineering development throughput",
      "Redesigned sprint coordination processes across cross-functional engineering teams",
      "Managed JIRA/Confluence workflows, sprint planning, and release tracking end-to-end",
      "Platform navigates 9,000+ cybersecurity solutions to match SMBs by profile, need, and budget",
    ],
    technologies: [
      "GenAI",
      "Agentic AI",
      "JIRA",
      "Confluence",
      "Agile",
      "Sprint Planning",
      "Product Discovery",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "9,000+",
    kpiLabel: "Solutions Navigated",
    kpiValue: "SMB Cybersecurity Platform",
    demoUrl: "https://valuealigners.com",
    youtubeUrl: "",
  },
  {
    id: "ntpc-jyoti-chatbot",
    slug: "ntpc-jyoti-enterprise-chatbot",
    title: "NTPC Jyoti – Enterprise AI Chatbot",
    image: "/projects/ntpc-chatbot.png",
    imageAlt: "NTPC Jyoti Enterprise AI Chatbot",
    briefDescription:
      "Developed NTPC's Enterprise AI chatbot 'Jyoti', enabling fast and secure enterprise data access for 20,000+ employees at India's largest power utility company.",
    problem:
      "NTPC's 20,000+ employees struggled to quickly access enterprise data and internal knowledge, leading to productivity loss and reliance on manual information retrieval processes across a large, distributed organization.",
    detailedDescription:
      "During my internship at NTPC Ltd (India's largest power utility), I co-developed 'Jyoti' — an Enterprise AI chatbot designed to give employees fast and secure access to enterprise data.\n\nThe chatbot enabled natural language querying of internal data, reducing the time employees spent searching for information and improving overall operational efficiency across the organization.",
    outcomeBullets: [
      "Deployed to 20,000+ NTPC employees",
      "Enabled fast, secure enterprise data access via natural language",
      "Reduced manual information retrieval across a large distributed org",
      "Built at India's largest power utility company",
    ],
    technologies: [
      "Python",
      "NLP",
      "REST APIs",
      "Enterprise AI",
      "SQL",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "20,000+",
    kpiLabel: "Employees Served",
    kpiValue: "Enterprise Deployment",
    demoUrl: "",
    youtubeUrl: "",
  },
{
  id: "studyhub",
  slug: "studyhub-resource-platform",
  title: "StudyHub! All-in-One Academic Resource Platform",
  image: "/projects/studyhub.png",
  imageAlt: "StudyHub – Centralized Academic Resource Platform",
  briefDescription:
    "Built a centralized academic platform aggregating study resources across 6+ engineering departments, simplifying access to notes, materials, and exam prep content. Peaked at 5,000+ concurrent users during exam seasons with zero paid acquisition.",
  problem:
    "Students relied on scattered sources like WhatsApp groups, Google Drive links, and seniors for study materials, making it time-consuming and inefficient to find reliable resources—especially during exams.",
  detailedDescription:
    "StudyHub is an all-in-one academic resource platform designed to simplify how students access study materials across multiple engineering disciplines.\n\nI conceptualized and structured the platform to centralize notes, previous year papers, and key resources for departments including Computer Science, Electronics, Electrical, Mechanical, Civil, and IT. The goal was to reduce friction in exam preparation by providing a single, reliable destination for all academic content. \n\n What validated the product most was its usage pattern — traffic spiked dramatically during exam seasons, peaking at 5,000+ concurrent users, proving genuine student reliance on the platform when it mattered most. This organic, need-driven adoption with zero paid acquisition demonstrated strong product-market fit",
  outcomeBullets: [
    "Centralized resources across 6+ engineering departments",
    "Reduced time spent searching for study materials during exams",
    "Eliminated dependency on scattered peer-to-peer sharing channels",
    "Improved accessibility and organization of academic content",
  ],
  technologies: [
    "Product Strategy",
    "User Research",
    "Content Structuring",
    "Information Architecture",
    "Web Platform",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "6+",
  kpiLabel: "Departments Covered",
  kpiValue: "Centralized Resource Platform",
  demoUrl: "https://studyhub.vinnovateit.com",
  youtubeUrl: "",
},  
{
  id: "creator-tool",
  slug: "creator-tool-platform",
  title: "Creator Tool – Scalable Content Platform",
  image: "/projects/creator-tool.png",
  imageAlt: "Creator Tool – Scalable Content Creation Platform",
  briefDescription:
    "Built backend architecture for a creator tool, leveraging AWS EC2 and S3 to enable scalable content storage and improve system reliability for high user traffic.",
  problem:
    "The existing creator platform lacked scalable backend infrastructure, leading to performance bottlenecks, unreliable content storage, and difficulty handling increasing user traffic and media uploads.",
  detailedDescription:
    "During my internship at Scrollify, I designed and developed the backend architecture for a creator tool used to manage and publish content at scale.\n\nI integrated AWS EC2 for compute scalability and S3 for secure, high-availability media storage. I also worked on optimizing API performance and structuring backend workflows to ensure reliable content delivery under increasing traffic loads.",
  outcomeBullets: [
    "Improved platform scalability to handle 2x increase in user traffic",
    "Reduced media load latency by ~30% through optimized storage architecture",
    "Enabled reliable storage and retrieval of high-volume content via AWS S3",
    "Strengthened backend stability and reduced system downtime",
  ],
  technologies: [
    "AWS EC2",
    "AWS S3",
    "Node.js",
    "REST APIs",
    "Backend Architecture",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "2x",
  kpiLabel: "Traffic Scalability",
  kpiValue: "Optimized Backend Infrastructure",
  demoUrl: "",
  youtubeUrl: "",
},
{
  id: "social-jumbos",
  slug: "social-jumbos-platform",
  title: "Social Jumbos – Event & Community Platform",
  image: "/projects/social-jumbos.png",
  imageAlt: "Social Jumbos – Event Organization & Community Platform",
  briefDescription:
    "Designed and built Social Jumbos, a platform enabling youth & students to discover, organize, and participate in interest based events with an integrated messaging system, university-specific spaces, and secure institutional login and verification.",
  problem:
    "Young individuals & University students lacked a dedicated platform to organize and discover self-organized campus events. Existing general-purpose tools like Facebook Groups, WhatsApp or posters lacked institutional context, verified identity, and a structured space for university-specific communities — leading to fragmented communication and low event participation.",
  detailedDescription:
    "Social Jumbos is a community and event platform built for young adults and university students. The platform enables students to create and join self-organized interest based events, coordinate with participants through an integrated messaging system, and engage within dedicated university-specific spaces.\n\nTo ensure trust and relevance, I designed and implemented a university-based authentication and verification system that validates institutional email addresses, restricting access to verified students and maintaining community integrity. The platform bridges the gap between social connection and campus life by giving students a structured, identity-verified space to build communities around shared interests and events.",
  outcomeBullets: [
    "Built end-to-end event discovery and organization platform for university students",
    "Integrated real-time messaging system for event participants and community members",
    "Designed university-specific spaces with institutional login and email verification",
    "Implemented secure authentication system ensuring verified student-only access",
    "Bridged gap between social connection and structured campus event management",
  ],
  technologies: [
    "Next.js",
    "TypeScript",
    "Node.js",
    "REST APIs",
    "Authentication",
    "Real-time Messaging",
    "PostgreSQL",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "University-Grade",
  kpiLabel: "Verified Access",
  kpiValue: "Institutional Auth System",
  demoUrl: "",
  youtubeUrl: "",
},
{
  id: "ai-smart-refrigerator",
  slug: "ai-smart-refrigerator-model",
  title: "AI Smart Refrigerator – Food Safety & Health Model",
  image: "/projects/smart-fridge.png",
  imageAlt: "AI Smart Refrigerator – Intelligent Food Monitoring System",
  briefDescription:
    "Designed an IoT-based AI smart refrigerator using computer vision and ML to identify food items, monitor quality, track liquid levels in bottles, and deliver personalized dietary insights — all accessible via an Android app in real time.",
  problem:
    "Traditional refrigerators offer no visibility into food inventory, quality, or expiry — leading to food waste, unhealthy eating habits, and unnecessary grocery trips. Users have no real-time awareness of what they have, what's expiring, or what they should be eating.",
  detailedDescription:
    "Built an intelligent refrigerator system that combines computer vision, IoT sensors, and machine learning to transform a standard fridge into a smart health and inventory management tool.\n\nA camera mounted inside the refrigerator continuously captures images, enabling real-time product identification and quantity estimation through image analysis. A multi-sensor system complements this by tracking the presence and quantity of various food items. A dedicated food quality monitoring module analyzes freshness to minimize waste by alerting users before items expire.\n\nAll insights are delivered through an Android application, giving users real-time visibility into their inventory and grocery needs from their phone. ML algorithms process the collected IoT data to identify dietary patterns and generate personalized health recommendations for the user.",
  outcomeBullets: [
    "Real-time food inventory tracking via in-fridge camera and computer vision",
    "Multi-sensor system for product identification and quantity estimation",
    "Food quality monitoring module to detect spoilage and minimize waste",
    "Android app delivering live inventory updates and grocery recommendations",
    "ML-driven dietary pattern analysis for personalized health insights",
    "Published research: Smart Refrigerator AI Model for Food Safety and Health Promotion using YOLOv10",
  ],
  technologies: [
    "YOLOv10",
    "Computer Vision",
    "IoT Sensors",
    "Machine Learning",
    "Android",
    "Python",
    "Image Analysis",
    "Raspberry Pi",
    "Firebase",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "YOLOv10",
  kpiLabel: "Computer Vision Model",
  kpiValue: "Food Safety & Health Promotion",
  demoUrl: "https://github.com/adityadotexe/Smart-Refrigerator-Model-YOLOv10/blob/main/AIP-%20Smart%20Refrigerator%20Model%20for%20Food%20Safety%20and%20Health%20promotion%20using%20YOLOv10.pdf",
  youtubeUrl: "",
},
{
  id: "foldpack-handle",
  slug: "foldpack-handle-product",
  title: "FoldPack Handle – Portable Load Distribution Solution",
  image: "/projects/foldpack-handle.jpeg",
  imageAlt: "FoldPack Handle – Ergonomic Grocery Load Distribution Product",
  briefDescription:
    "Designed and developed FoldPack Handle, a compact, ergonomic load-distribution solution with an integrated reusable bag, improving carrying comfort and targeting urban grocery users.",
  problem:
    "Urban shoppers, often carry multiple grocery bags, leading to hand strain, discomfort, and inefficient load distribution. Existing solutions either lacked portability or failed to address ergonomic pain points effectively.",
  detailedDescription:
    "As part of a product development initiative, I led the conceptualization and strategic development of FoldPack Handle—an ergonomic, pocket-sized solution designed to improve the grocery carrying experience.\n\nThe product features a reinforced polymer handle with multiple bag hooks, an integrated foldable reusable bag with a shoulder-strap carrying mode, enabling users to distribute weight efficiently while maintaining portability. I worked on defining the product design, positioning, pricing strategy, and go-to-market approach, focusing on urban consumers and high-frequency grocery shoppers.",
  outcomeBullets: [
    "Defined a scalable consumer product with ~61% contribution margin",
    "Unique standout market feature of Dual carry-mode-> Hand & Shoulder with a built-in high quality reusable bag",
    "Identified a target market of 3–5M urban early adopers in the U.S.",
    "Projected first-year sales of ~18,000 units based on market analysis",
    "Positioned product competitively against alternatives like tote bags and handle grips",
  ],
  technologies: [
    "Product Strategy",
    "Market Research",
    "Pricing Strategy",
    "Go-to-Market Planning",
    "Consumer Product Design",
  ],
  status: "Concept / In Development",
  statusColor: "yellow",
  isFeatured: true,
  kpi: "61%",
  kpiLabel: "Contribution Margin",
  kpiValue: "High-Margin Consumer Product",
  demoUrl: "",
  youtubeUrl: "",
}
]