import type { Project } from "./types"

export const projectsData: Project[] = [
  {
    id: "messit",
    slug: "messit-dining-platform",
    title: "MessIT – Digital Dining Platform",
    image: "/projects/messit.jpg",
    imageAlt: "MessIT – Digital Dining Platform for University Students",
    briefDescription:
      "Led product development of MessIT, a digital dining platform adopted by 10,000+ students, replacing manual mess-menu processes with a seamless digital experience.",
    problem:
      "University dining was entirely manual — students had no visibility into daily menus, couldn't provide structured feedback, and administrators had no data to improve operations. The process was slow, inefficient, and frustrating for 10,000+ students.",
    detailedDescription:
      "MessIT is a digital dining platform built to replace the outdated manual mess-menu processes at a large university. As the product lead, I drove the end-to-end development — from user discovery and requirements gathering to launch and adoption.\n\nThe platform gave students real-time access to daily menus, enabled structured feedback collection, and provided administrators with actionable data to improve dining operations.",
    outcomeBullets: [
      "Adopted by 10,000+ students across the university",
      "Replaced 100% of manual mess-menu processes",
      "Enabled structured feedback collection for dining administrators",
      "Improved operational visibility and menu planning efficiency",
    ],
    technologies: [
      "Product Strategy",
      "User Research",
      "Agile",
      "PRD",
      "Roadmapping",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "10,000+",
    kpiLabel: "Students Adopted",
    kpiValue: "Full Campus Rollout",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "bunkbuddies",
    slug: "bunkbuddies-roommate-matching",
    title: "BunkBuddies – Roommate Matching Platform",
    image: "/projects/bunkbuddies.png",
    imageAlt: "BunkBuddies – University Roommate Matching Platform",
    briefDescription:
      "Drove end-to-end launch as Project Lead of the university's first roommate matching platform, gaining 1,250+ users on launch day.",
    problem:
      "Finding a compatible roommate at university was entirely word-of-mouth — no structured platform existed. Students relied on social media groups and random assignments, leading to poor roommate compatibility and avoidable conflicts.",
    detailedDescription:
      "BunkBuddies was the university's first dedicated roommate matching platform. As Project Lead, I owned the full product lifecycle — from identifying the problem through user interviews to defining matching criteria, coordinating the engineering team, and executing the launch strategy.\n\nThe platform matched students based on lifestyle preferences, study habits, and personal preferences, significantly improving roommate compatibility.",
    outcomeBullets: [
      "1,250+ users acquired on launch day",
      "First-ever roommate matching platform at the university",
      "Drove full end-to-end product launch as Project Lead",
      "Replaced unstructured social media roommate search process",
    ],
    technologies: [
      "Product Management",
      "User Discovery",
      "MVP Development",
      "Launch Strategy",
      "A/B Testing",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "1,250+",
    kpiLabel: "Users on Launch Day",
    kpiValue: "University's First Platform",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "ai-whatsapp-navigator",
    slug: "ai-whatsapp-patient-navigator",
    title: "AI-Powered WhatsApp Patient Navigator",
    image: "/projects/jc-foundation.png",
    imageAlt: "AI WhatsApp Navigator – Automated Patient Guidance System",
    briefDescription:
      "Deployed an AI-powered WhatsApp navigator using NLP models to automate end-to-end patient guidance for a secondary consultation platform serving 500+ patients/month, reducing wait times by 15%.",
    problem:
      "JC Foundation's secondary consultation platform served 500+ cancer patients per month but struggled with high manual overhead in patient guidance. Long wait times and inconsistent communication created friction in an already stressful patient journey.",
    detailedDescription:
      "At JC Foundation, I defined the product roadmap and feature requirements for an AI-enabled secondary consultation platform. The flagship feature was an AI-powered WhatsApp navigator that used NLP models to automate the end-to-end patient guidance journey.\n\nI also conducted 30+ user discovery interviews with oncologists to map workflows, identify bottlenecks, and validate pricing models — ensuring the product was grounded in real clinical needs.",
    outcomeBullets: [
      "15% reduction in patient wait times",
      "500+ patients served per month on the platform",
      "Automated end-to-end patient guidance via WhatsApp",
      "30+ oncologist interviews conducted for user discovery",
      "Defined full product roadmap and feature requirements",
    ],
    technologies: [
      "NLP",
      "WhatsApp Business API",
      "Product Roadmapping",
      "User Research",
      "PRD",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "15%",
    kpiLabel: "Wait Time Reduction",
    kpiValue: "500+ Patients/Month",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "agentic-ai-platform",
    slug: "agentic-ai-cybersecurity-platform",
    title: "Agentic AI Platform – Cybersecurity SMB Navigator",
    image: "/projects/agentic-ai.png",
    imageAlt: "Agentic AI Platform for SMB Cybersecurity Navigation",
    briefDescription:
      "Led GenAI product analysis and feature discovery for an Agentic AI platform helping SMBs navigate 9,000+ cybersecurity solutions, while implementing coordination processes that improved engineering development throughput.",
    problem:
      "SMBs face an overwhelming cybersecurity landscape with 9,000+ solutions and no clear guidance on what they actually need. Value Aligners needed to define the right AI-powered features to cut through this complexity and deliver actionable recommendations.",
    detailedDescription:
      "At Value Aligners, I led GenAI product analysis and feature discovery for an Agentic AI platform designed to help SMBs navigate the complex cybersecurity market. My work spanned product strategy, engineering coordination, and release management.\n\nI identified release bottlenecks across engineering teams and implemented coordination processes that directly improved development throughput. I also managed JIRA and Confluence workflows, sprint planning, and release tracking to ensure feature validation and milestone completion.",
    outcomeBullets: [
      "Led feature discovery for platform navigating 9,000+ cybersecurity solutions",
      "Identified and resolved release bottlenecks across engineering teams",
      "Improved development throughput through coordination process redesign",
      "Managed sprint planning, JIRA/Confluence workflows, and release tracking",
    ],
    technologies: [
      "GenAI",
      "Agentic AI",
      "JIRA",
      "Confluence",
      "Agile",
      "Sprint Planning",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "9,000+",
    kpiLabel: "Solutions Navigated",
    kpiValue: "SMB Cybersecurity Platform",
    demoUrl: "",
    youtubeUrl: "",
  },
  {
    id: "ntpc-jyoti-chatbot",
    slug: "ntpc-jyoti-enterprise-chatbot",
    title: "NTPC Jyoti – Enterprise AI Chatbot",
    image: "/projects/ntpc-chatbot.png",
    imageAlt: "NTPC Jyoti Enterprise AI Chatbot",
    briefDescription:
      "Co-developed NTPC's Enterprise AI chatbot 'Jyoti', enabling fast and secure enterprise data access for 20,000+ employees at India's largest power utility company.",
    problem:
      "NTPC's 20,000+ employees struggled to quickly access enterprise data and internal knowledge, leading to productivity loss and reliance on manual information retrieval processes across a large, distributed organization.",
    detailedDescription:
      "During my internship at NTPC Ltd (India's largest power utility), I co-developed 'Jyoti' — an Enterprise AI chatbot designed to give employees fast and secure access to enterprise data.\n\nThe chatbot enabled natural language querying of internal data, reducing the time employees spent searching for information and improving overall operational efficiency across the organization.",
    outcomeBullets: [
      "Deployed to 20,000+ NTPC employees",
      "Enabled fast, secure enterprise data access via natural language",
      "Reduced manual information retrieval across a large distributed org",
      "Built at India's largest power utility company",
    ],
    technologies: [
      "Python",
      "NLP",
      "REST APIs",
      "Enterprise AI",
      "SQL",
    ],
    status: "Active",
    statusColor: "green",
    isFeatured: true,
    kpi: "20,000+",
    kpiLabel: "Employees Served",
    kpiValue: "Enterprise Deployment",
    demoUrl: "",
    youtubeUrl: "",
  },
{
  id: "studyhub",
  slug: "studyhub-resource-platform",
  title: "StudyHub! All-in-One Academic Resource Platform",
  image: "/projects/studyhub.png",
  imageAlt: "StudyHub – Centralized Academic Resource Platform",
  briefDescription:
    "Built a centralized academic platform aggregating study resources across 6+ engineering departments, simplifying access to notes, materials, and exam prep content.",
  problem:
    "Students relied on scattered sources like WhatsApp groups, Google Drive links, and seniors for study materials, making it time-consuming and inefficient to find reliable resources—especially during exams.",
  detailedDescription:
    "StudyHub is an all-in-one academic resource platform designed to simplify how students access study materials across multiple engineering disciplines.\n\nI conceptualized and structured the platform to centralize notes, previous year papers, and key resources for departments including Computer Science, Electronics, Electrical, Mechanical, Civil, and IT. The goal was to reduce friction in exam preparation by providing a single, reliable destination for all academic content.",
  outcomeBullets: [
    "Centralized resources across 6+ engineering departments",
    "Reduced time spent searching for study materials during exams",
    "Eliminated dependency on scattered peer-to-peer sharing channels",
    "Improved accessibility and organization of academic content",
  ],
  technologies: [
    "Product Strategy",
    "User Research",
    "Content Structuring",
    "Information Architecture",
    "Web Platform",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "6+",
  kpiLabel: "Departments Covered",
  kpiValue: "Centralized Resource Platform",
  demoUrl: "",
  youtubeUrl: "",
},  
{
  id: "creator-tool",
  slug: "creator-tool-platform",
  title: "Creator Tool – Scalable Content Platform",
  image: "/projects/creator-tool.png",
  imageAlt: "Creator Tool – Scalable Content Creation Platform",
  briefDescription:
    "Built backend architecture for a creator tool, leveraging AWS EC2 and S3 to enable scalable content storage and improve system reliability for high user traffic.",
  problem:
    "The existing creator platform lacked scalable backend infrastructure, leading to performance bottlenecks, unreliable content storage, and difficulty handling increasing user traffic and media uploads.",
  detailedDescription:
    "During my internship at Scrollify, I designed and developed the backend architecture for a creator tool used to manage and publish content at scale.\n\nI integrated AWS EC2 for compute scalability and S3 for secure, high-availability media storage. I also worked on optimizing API performance and structuring backend workflows to ensure reliable content delivery under increasing traffic loads.",
  outcomeBullets: [
    "Improved platform scalability to handle 2x increase in user traffic",
    "Reduced media load latency by ~30% through optimized storage architecture",
    "Enabled reliable storage and retrieval of high-volume content via AWS S3",
    "Strengthened backend stability and reduced system downtime",
  ],
  technologies: [
    "AWS EC2",
    "AWS S3",
    "Node.js",
    "REST APIs",
    "Backend Architecture",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "2x",
  kpiLabel: "Traffic Scalability",
  kpiValue: "Optimized Backend Infrastructure",
  demoUrl: "",
  youtubeUrl: "",
},
{
  id: "social-jumbos",
  slug: "social-jumbos-platform",
  title: "Social Jumbos – Event & Community Platform",
  image: "/projects/social-jumbos.png",
  imageAlt: "Social Jumbos – Event Organization & Community Platform",
  briefDescription:
    "Designed and built Social Jumbos, a campus-focused platform enabling students to discover, organize, and participate in events with an integrated messaging system, university-specific spaces, and secure institutional login and verification.",
  problem:
    "University students lacked a dedicated platform to organize and discover campus events. Existing general-purpose tools like Facebook Groups or WhatsApp lacked institutional context, verified identity, and a structured space for university-specific communities — leading to fragmented communication and low event participation.",
  detailedDescription:
    "Social Jumbos is a community and event platform built specifically for university students. The platform enables students to create and join events, coordinate with participants through an integrated messaging system, and engage within dedicated university-specific spaces.\n\nTo ensure trust and relevance, I designed and implemented a university-based authentication and verification system that validates institutional email addresses, restricting access to verified students and maintaining community integrity. The platform bridges the gap between social connection and campus life by giving students a structured, identity-verified space to build communities around shared interests and events.",
  outcomeBullets: [
    "Built end-to-end event discovery and organization platform for university students",
    "Integrated real-time messaging system for event participants and community members",
    "Designed university-specific spaces with institutional login and email verification",
    "Implemented secure authentication system ensuring verified student-only access",
    "Bridged gap between social connection and structured campus event management",
  ],
  technologies: [
    "Next.js",
    "TypeScript",
    "Node.js",
    "REST APIs",
    "Authentication",
    "Real-time Messaging",
    "PostgreSQL",
  ],
  status: "Active",
  statusColor: "green",
  isFeatured: true,
  kpi: "University-Grade",
  kpiLabel: "Verified Access",
  kpiValue: "Institutional Auth System",
  demoUrl: "",
  youtubeUrl: "",
},
{
  id: "foldpack-handle",
  slug: "foldpack-handle-product",
  title: "FoldPack Handle – Portable Load Distribution Solution",
  image: "/projects/foldpack-handle.jpeg",
  imageAlt: "FoldPack Handle – Ergonomic Grocery Load Distribution Product",
  briefDescription:
    "Designed and developed FoldPack Handle, a compact, ergonomic load-distribution solution with an integrated reusable bag, improving carrying comfort and targeting urban grocery users.",
  problem:
    "Urban shoppers, especially students and professionals, often carry multiple grocery bags, leading to hand strain, discomfort, and inefficient load distribution. Existing solutions either lacked portability or failed to address ergonomic pain points effectively.",
  detailedDescription:
    "As part of a product development initiative, I led the conceptualization and strategic development of FoldPack Handle—an ergonomic, pocket-sized solution designed to improve the grocery carrying experience.\n\nThe product features a reinforced polymer handle with multiple bag hooks and an integrated foldable reusable bag, enabling users to distribute weight efficiently while maintaining portability. I worked on defining the product design, positioning, pricing strategy, and go-to-market approach, focusing on urban consumers and high-frequency grocery shoppers.",
  outcomeBullets: [
    "Defined a scalable consumer product with ~61% contribution margin",
    "Identified a target market of 3–5M urban early adopers in the U.S.",
    "Projected first-year sales of ~18,000 units based on market analysis",
    "Positioned product competitively against alternatives like tote bags and handle grips",
  ],
  technologies: [
    "Product Strategy",
    "Market Research",
    "Pricing Strategy",
    "Go-to-Market Planning",
    "Consumer Product Design",
  ],
  status: "Concept / In Development",
  statusColor: "yellow",
  isFeatured: true,
  kpi: "61%",
  kpiLabel: "Contribution Margin",
  kpiValue: "High-Margin Consumer Product",
  demoUrl: "",
  youtubeUrl: "",
}
]